// Setup your quiz text and questions here

// NOTE: pay attention to commas, IE struggles with those bad boys

var quizJSON = {
    "info": {
        "name":    "Cellular Respiration",
        "main":    "%total questions (Campbell Test Bank 8e)",
        "results": "" // no comma here
    },
    "questions": [
        {
            "q": "The molecule that functions as the reducing agent in a redox reaction",
            "a": [
                {"option": "gains electrons and gains energy.", "correct":false},
                {"option": "loses electrons and loses energy. ", "correct":true},
                {"option": "gains electrons and loses energy. ", "correct":false},
                {"option": "loses electrons and gains energy.", "correct":false},
                {"option": "neither gains nor loses electrons, but gains or loses energy.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which of the following statements describes the results of this reaction? C6H12O6 + 6 O2 → 6 CO2 + 6 H2O + Energy",
            "a": [
                {"option": "C6H12O6 is oxidized and O2 is reduced. ", "correct":true},
                {"option": "O2 is oxidized and H2O is reduced.", "correct":false},
                {"option": "CO2 is reduced and O2 is oxidized.", "correct":false},
                {"option": "C6H12O6 is reduced and CO2 is oxidized. ", "correct":false},
                {"option": "O2 is reduced and CO2 is oxidized.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "When a molecule of NAD+ gains a hydrogen atom the molecule becomes",
            "a": [
                {"option": "hydrogenated. ", "correct":false},
                {"option": "oxidized.", "correct":false},
                {"option": "reduced. ", "correct":true},
                {"option": "redoxed.", "correct":false},
                {"option": "a reducing agent.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which of the following statements describes NAD +?",
            "a": [
                {"option": "NAD+ is reduced to NADH during both glycolysis and the citric acid cycle. ", "correct":true},
                {"option": "NAD+ has more chemical energy than NADH.", "correct":false},
                {"option": "NAD+ is reduced by the action of hydrogenases.", "correct":false},
                {"option": "NAD+ can donate electrons for use in oxidative phosphorylation. ", "correct":false},
                {"option": "In the absence of NAD+, glycolysis can still function.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Where does glycolysis takes place?",
            "a": [
                {"option": "mitochondrial matrix", "correct":false},
                {"option": "mitochondrial outer membrane", "correct":false},
                {"option": "mitochondrial inner membrane", "correct":false},
                {"option": "mitochondrial intermembrane space", "correct":false},
                {"option": "cytosol", "correct":true} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "The ATP made during glycolysis is generated by",
            "a": [
                {"option": "substrate-level phosphorylation. ", "correct":true},
                {"option": "electron transport.", "correct":false},
                {"option": "photophosphorylation.", "correct":false},
                {"option": "chemiosmosis.", "correct":false},
                {"option": "oxidation of NADH to NAD+. ", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "The oxygen consumed during cellular respiration is involved directly in which process or event?",
            "a": [
                {"option": "glycolysis", "correct":false},
                {"option": "accepting electrons at the end of the electron transport chain", "correct":true},
                {"option": "the citric acid cycle", "correct":false},
                {"option": "the oxidation of pyruvate to acetyl CoA", "correct":false},
                {"option": "the phosphorylation of ADP to form ATP", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which process in eukaryotic cells will proceed normally when oxygen is absent?",
            "a": [
                {"option": "electron transport", "correct":false},
                {"option": "glycolysis", "correct":true},
                {"option": "the citric acid cycle", "correct":false},
                {"option": "oxidative phosphorylation", "correct":false},
                {"option": "chemiosmosis", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "An electron loses potential energy when it",
            "a": [
                {"option": "shifts to a less electronegative atom. ", "correct":false},
                {"option": "shifts to a more electronegative atom. ", "correct":true},
                {"option": "increases its kinetic energy.", "correct":false},
                {"option": "increases its activity as an oxidizing agent.", "correct":false},
                {"option": "attaches itself to NAD+. ", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Substrate-level phosphorylation accounts for approximately what percentage of the ATP formed during glycolysis?",
            "a": [
                {"option": "0% ", "correct":false},
                {"option": "2% ", "correct":false},
                {"option": "10% ", "correct":false},
                {"option": "38%", "correct":false},
                {"option": "100%", "correct":true} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "In addition to ATP, what are the end products of glycolysis?",
            "a": [
                {"option": "CO2 and H2O", "correct":false},
                {"option": "CO2 and pyruvate", "correct":false},
                {"option": "NADH and pyruvate", "correct":true},
                {"option": "CO2 and NADH", "correct":false},
                {"option": "H2O, FADH2, and citrate", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "In glycolysis, for each molecule of glucose oxidized to pyruvate",
            "a": [
                {"option": "2 molecules of ATP are used and 2 molecules of ATP are produced. ", "correct":false},
                {"option": "2 molecules of ATP are used and 4 molecules of ATP are produced. ", "correct":true},
                {"option": "4 molecules of ATP are used and 2 molecules of ATP are produced. ", "correct":false},
                {"option": "2 molecules of ATP are used and 6 molecules of ATP are produced. ", "correct":false},
                {"option": "6 molecules of ATP are used and 6 molecules of ATP are produced.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which kind of metabolic poison would most directly interfere with glycolysis?",
            "a": [
                {"option": "an agent that reacts with oxygen and depletes its concentration in the cell", "correct":false},
                {"option": "an agent that binds to pyruvate and inactivates it", "correct":false},
                {"option": "an agent that closely mimics the structure of glucose but is not metabolized", "correct":true},
                {"option": "an agent that reacts with NADH and oxidizes it to NAD+", "correct":false},
                {"option": "an agent that blocks the passage of electrons along the electron transport chain", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Pyruvate oxidation results in the formation of",
            "a": [
                {"option": "acetyl CoA, O2, and ATP.", "correct":false},
                {"option": "acetyl CoA, FADH2, and CO2.", "correct":false},
                {"option": "acetyl CoA, FAD, H2, and CO2.", "correct":false},
                {"option": "acetyl CoA, NADH, H+, and CO2. ", "correct":true},
                {"option": "acetyl CoA, NAD+, ATP, and CO2.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which of the following would be produced from four turns of the citric acid cycle?",
            "a": [
                {"option": "1 FADH2 and 4 NADH ", "correct":false},
                {"option": "2 FADH2 and 8 NADH ", "correct":false},
                {"option": "4 FADH2 and 12 NADH ", "correct":true},
                {"option": "1 FAD and 4 NAD+", "correct":false},
                {"option": "4 FAD+ and 12 NAD+", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Which of the following combinations of products would result from three turns of the citric acid cycle?",
            "a": [
                {"option": "1 ATP, 2 CO2, 3 NADH, and 1 FADH2", "correct":false},
                {"option": "2 ATP, 2 CO2, 1 NADH, and 3 FADH2", "correct":false},
                {"option": "3 ATP, 3 CO2, 3 NADH, and 3 FADH2", "correct":false},
                {"option": "3 ATP, 6 CO2, 9 NADH, and 3 FADH2", "correct":true},
                {"option": "38 ATP, 6 CO2, 3 NADH, and 12 FADH2", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Carbon dioxide (CO2) is released during which of the following stages of cellular respiration?",
            "a": [
                {"option": "glycolysis and pyruvate oxidation", "correct":false},
                {"option": "pyruvate oxidation and the citric acid cycle", "correct":true},
                {"option": "the citric acid cycle and oxidative phosphorylation", "correct":false},
                {"option": "oxidative phosphorylation and fermentation", "correct":false},
                {"option": "fermentation and glycolysis", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "During cellular respiration, electrons travel downhill in which sequence?",
            "a": [
                {"option": "food → citric acid cycle → ATP → NAD+", "correct":false},
                {"option": "food → NADH → electron transport chain → oxygen", "correct":true},
                {"option": "glucose → pyruvate → ATP → oxygen", "correct":false},
                {"option": "glucose → ATP → electron transport chain → NADH ", "correct":false},
                {"option": "food → glycolysis → citric acid cycle → NADH → ATP", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "During aerobic respiration, which of the following directly donates electrons to the electron transport chain at the lowest energy level?",
            "a": [
                {"option": "NAD+ ", "correct":false},
                {"option": "NADH ", "correct":false},
                {"option": "ATP", "correct":false},
                {"option": "ADP + Pi", "correct":false},
                {"option": "FADH2", "correct":true} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "The primary role of oxygen in cellular respiration is to",
            "a": [
                {"option": "yield energy in the form of ATP as it is passed down the respiratory chain.", "correct":false},
                {"option": "act as an acceptor for electrons and hydrogen, forming water. ", "correct":true},
                {"option": "combine with carbon, forming CO2.", "correct":false},
                {"option": "combine with lactate, forming pyruvate.", "correct":false},
                {"option": "catalyze the reactions of glycolysis.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "The direct energy source that drives ATP synthesis during oxidative phosphorylation is",
            "a": [
                {"option": "oxidation of glucose to CO2 and water.", "correct":false},
                {"option": "the thermodynamically favorable flow of electrons from NADH to the mitochondrial electron transport carriers.", "correct":false},
                {"option": "the final transfer of electrons to oxygen.", "correct":false},
                {"option": "the difference in H+ concentrations on opposite sides of the inner mitochondrial membrane.", "correct":true},
                {"option": "the thermodynamically favorable transfer of phosphate from glycolysis and the citric acid cycle intermediate molecules of ADP.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Energy released by the electron transport chain is used to pump H+ ions into which location?",
            "a": [
                {"option": "cytosol", "correct":false},
                {"option": "mitochondrial outer membrane", "correct":false},
                {"option": "mitochondrial inner membrane", "correct":false},
                {"option": "mitochondrial intermembrane space", "correct":true},
                {"option": "mitochondrial matrix", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "In liver cells, the inner mitochondrial membranes are about 5x the area of the outer mitochondrial membranes, and about 17x that of the cellʹs plasma membrane. What purpose must this serve?",
            "a": [
                {"option": "It allows for increased rate of glycolysis.", "correct":false},
                {"option": "It allows for increased rate of the citric acid cycle.", "correct":false},
                {"option": "It increases the surface for oxidative phosphoryation.", "correct":true},
                {"option": "It increases the surface for substrate-level phosphorylation. ", "correct":false},
                {"option": "It allows the liver cell to have fewer mitochondria.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "The ATP made during fermentation is generated by which of the following?",
            "a": [
                {"option": "the electron transport chain", "correct":false},
                {"option": "substrate-level phosphorylation", "correct":true},
                {"option": "chemiosmosis", "correct":false},
                {"option": "oxidative phosphorylation", "correct":false},
                {"option": "aerobic respiration", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "In fermentation in yeast, NAD+ is regenerated from NADH during which of the following?",
            "a": [
                {"option": "reduction of acetaldehyde to ethanol (ethyl alcohol) ", "correct":true},
                {"option": "oxidation of pyruvate to acetyl CoA", "correct":false},
                {"option": "reduction of pyruvate to form lactate", "correct":false},
                {"option": "oxidation of NAD+ in the citric acid cycle", "correct":false},
                {"option": "phosphorylation of ADP to form ATP", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "One function of both alcohol fermentation and lactic acid fermentation is to",
            "a": [
                {"option": "reduce NAD+ to NADH. ", "correct":false},
                {"option": "reduce FAD+ to FADH2. ", "correct":false},
                {"option": "oxidize NADH to NAD+. ", "correct":true},
                {"option": "reduce FADH2 to FAD+. ", "correct":false},
                {"option": "none of the above", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Why is glycolysis considered to be one of the first metabolic pathways to have evolved?",
            "a": [
                {"option": "It produces much less ATP than does oxidative phosphorylation.", "correct":false},
                {"option": "It is found in the cytosol, does not involve oxygen, and is present in most organisms.", "correct":true},
                {"option": "It is found in prokaryotic cells but not in eukaryotic cells.", "correct":false},
                {"option": "It relies on chemiosmosis which is a metabolic mechanism present only in the first cells-prokaryotic cells.", "correct":false},
                {"option": "It requires the presence of membrane-enclosed cell organelles found only in eukaryotic cells.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "What is the purpose of beta oxidation in respiration?",
            "a": [
                {"option": "oxidation of glucose ", "correct":false},
                {"option": "oxidation of pyruvate ", "correct":false},
                {"option": "feedback regulation", "correct":false},
                {"option": "control of ATP accumulation", "correct":false},
                {"option": "breakdown of fatty acids", "correct":true} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Where do the catabolic products of fatty acid breakdown enter into the citric acid cycle?",
            "a": [
                {"option": "pyruvate", "correct":false},
                {"option": "malate or fumarate", "correct":false},
                {"option": "acetyl CoA", "correct":true},
                {"option": "α-ketoglutarate", "correct":false},
                {"option": "succinyl CoA", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "What is the reducing agent in the following reaction? Pyruvate + NADH + H+ → Lactate + NAD+",
            "a": [
                {"option": "oxygen", "correct":false},
                {"option": "NADH", "correct":true},
                {"option": "NAD+", "correct":false},
                {"option": "lactate", "correct":false},
                {"option": "pyruvate", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "When electrons flow along the electron transport chains of mitochondria, which of the following changes occurs?",
            "a": [
                {"option": "The pH of the matrix increases.", "correct":true},
                {"option": "ATP synthase pumps protons by active transport.", "correct":false},
                {"option": "The electrons gain free energy.", "correct":false},
                {"option": "The cytochromes phosphorylate ADP to form ATP.", "correct":false},
                {"option": "NAD+ is oxidized. ", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        },
        {
            "q": "Most CO2 from cellular respiration is released during",
            "a": [
                {"option": "glycolysis.", "correct":false},
                {"option": "the citric acid cycle. ", "correct":true},
                {"option": "lactate fermentation. ", "correct":false},
                {"option": "electron transport.", "correct":false},
                {"option": "oxidative phosphorylation.", "correct":false} // no comma here
            ],
            "correct": "<p><span>Correct</span></p>",
            "incorrect": "<p><span>Incorrect</span></p>" // no comma here 
        }
  ]
};
